require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("plugins.plugin-setup")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")

require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
require("plugins.lsp.rust")

require("plugins.treesitter")
require("plugins.ctrlsf")
-- require("josean.plugins.gitsigns")
--
